export interface Review {
  name: string
  location: string
  product: string
  rating: number
  date: string
  title: string
  body: string
  verified: boolean
}

export const REVIEW_STATS = {
  average: 4.9,
  total: 2847,
  fiveStar: 91,
  fourStar: 7,
  threeStar: 2,
}

export const REVIEWS: Review[] = [
  {
    name: 'Aarav Sharma',
    location: 'Mumbai, India',
    product: 'Re Di Ferro',
    rating: 5,
    date: 'May 2026',
    title: 'My new signature, without question',
    body: 'I wore Re Di Ferro to a wedding in Udaipur and I lost count of how many people asked what I was wearing. It opens sharp and confident, then settles into something warm and expensive. Lasts the entire day and night.',
    verified: true,
  },
  {
    name: 'Jessica Williams',
    location: 'Austin, USA',
    product: 'Veleno D’Oro',
    rating: 5,
    date: 'May 2026',
    title: 'Dangerously addictive',
    body: 'The name is no joke. My husband keeps stealing it off my dresser. It is rich and a little bit sinful — saffron and rose with that smoky oud underneath. Worth every penny.',
    verified: true,
  },
  {
    name: 'Priya Nair',
    location: 'Bengaluru, India',
    product: 'Notte Eterna',
    rating: 5,
    date: 'April 2026',
    title: 'Romance in a bottle',
    body: 'Notte Eterna is the most elegant thing I own. The cherry and plum at the top feel festive, and by night it turns into this soft vanilla-oud trail. I get compliments every single time.',
    verified: true,
  },
  {
    name: 'Lucas Müller',
    location: 'Munich, Germany',
    product: 'Il Sovrano',
    rating: 5,
    date: 'April 2026',
    title: 'Truly regal projection',
    body: 'Extrait concentration and you can tell. Two sprays in the morning and people in the lift still notice it at 6pm. Sophisticated, never loud. This is old-money elegance done right.',
    verified: true,
  },
  {
    name: 'Ananya Iyer',
    location: 'Chennai, India',
    product: 'Palazzo Delle Ombre',
    rating: 5,
    date: 'April 2026',
    title: 'Mysterious and grown-up',
    body: 'I wanted something that did not smell like everything else at the office. Palazzo Delle Ombre is iris and tobacco flower and a little smoke — refined and a bit secretive. Exactly what I hoped for.',
    verified: true,
  },
  {
    name: 'Michael Johnson',
    location: 'Chicago, USA',
    product: 'Imperatore Nero',
    rating: 5,
    date: 'March 2026',
    title: 'Commands the room',
    body: 'Bought this for my anniversary and my wife will not let me wear anything else now. Cognac, rose and tonka — it is bold but classy. The bottle alone looks like a thousand dollars on the shelf.',
    verified: true,
  },
  {
    name: 'Sneha Kapoor',
    location: 'Delhi, India',
    product: 'L’Ultima Medici',
    rating: 5,
    date: 'March 2026',
    title: 'The signature scent lives up to the hype',
    body: 'This is the one everyone talks about and it deserves it. It feels like inheritance — warm, golden, timeless. I gifted a bottle to my father and he was genuinely moved. Packaging is immaculate.',
    verified: true,
  },
  {
    name: 'Sofia Rossi',
    location: 'Milan, Italy',
    product: 'Portofino Imperiale',
    rating: 5,
    date: 'March 2026',
    title: 'Bellissimo — smells like the Riviera',
    body: 'As an Italian I am very particular, and Portofino Imperiale is fresh, green and luxurious all at once. It reminds me of summers on the coast. Bravo, Bolly.',
    verified: true,
  },
  {
    name: 'Omar Al-Farsi',
    location: 'Dubai, UAE',
    product: 'Duca Nero',
    rating: 5,
    date: 'February 2026',
    title: 'Finally an oud that feels modern',
    body: 'We know our oud here, and Duca Nero is exceptional. Deep and a little spicy without being heavy or old-fashioned. The longevity is incredible — I can still smell it on my kandura the next morning.',
    verified: true,
  },
  {
    name: 'Emily Davis',
    location: 'London, UK',
    product: 'Notte Eterna',
    rating: 4,
    date: 'February 2026',
    title: 'Beautiful, wish it lasted a touch longer',
    body: 'Genuinely gorgeous scent and the compliments are real. I take off half a star only because on my skin it softens after about six hours. Still buying again.',
    verified: true,
  },
  {
    name: 'Rohan Mehta',
    location: 'Pune, India',
    product: 'Il Sovrano',
    rating: 5,
    date: 'February 2026',
    title: 'Worth the upgrade from my old designer bottle',
    body: 'I used to wear the usual department-store names. Switched to Il Sovrano and there is no comparison — it smells richer and far more unique. The specialist at the kiosk helped me pick it and nailed it.',
    verified: true,
  },
  {
    name: 'Chen Wei',
    location: 'Singapore',
    product: 'Veleno D’Oro',
    rating: 5,
    date: 'January 2026',
    title: 'Elegant and unforgettable',
    body: 'Bought this on a whim after testing at the kiosk and I have zero regrets. It is sweet but sophisticated, perfect for evenings. Three people asked me about it at dinner.',
    verified: true,
  },
  {
    name: 'Isabella García',
    location: 'Madrid, Spain',
    product: 'Palazzo Delle Ombre',
    rating: 5,
    date: 'January 2026',
    title: 'My everyday luxury',
    body: 'I reach for this every morning. It is understated and chic, never overpowering. The kind of fragrance that makes people lean in to ask instead of stepping back.',
    verified: true,
  },
  {
    name: 'Karthik Subramaniam',
    location: 'Hyderabad, India',
    product: 'Re Di Ferro',
    rating: 5,
    date: 'December 2025',
    title: 'Powerful and premium',
    body: 'Gifted to myself after a promotion and it feels exactly like the occasion. Strong, masculine, and refined. The black bottle with the gold cap is a statement piece on its own.',
    verified: true,
  },
  {
    name: 'Olivia Thompson',
    location: 'Toronto, Canada',
    product: 'L’Ultima Medici',
    rating: 5,
    date: 'December 2025',
    title: 'Obsessed — this is art',
    body: 'I collect niche fragrances and L’Ultima Medici holds its own against bottles twice the price. Warm amber and incense, beautifully blended. The unboxing felt like a ceremony.',
    verified: true,
  },
  {
    name: 'Meera Joshi',
    location: 'Ahmedabad, India',
    product: 'Imperatore Nero',
    rating: 5,
    date: 'December 2025',
    title: 'Bold, confident, addictive',
    body: 'Not for the shy. This is a head-turner — warm spice and rose that lingers gorgeously. My sister immediately ordered her own bottle after smelling mine.',
    verified: true,
  },
  {
    name: 'James Anderson',
    location: 'Sydney, Australia',
    product: 'Duca Nero',
    rating: 4,
    date: 'November 2025',
    title: 'Excellent scent, premium feel',
    body: 'Really impressed with the quality and the projection. Took half a star off only because I wish it came in a travel size. Otherwise a fantastic, distinctive fragrance.',
    verified: true,
  },
  {
    name: 'Fatima Khan',
    location: 'Lahore, Pakistan',
    product: 'Notte Eterna',
    rating: 5,
    date: 'November 2025',
    title: 'Romantic and rich',
    body: 'I wore this to my engagement and it was perfect — soft florals with a deep sweet base. Everyone kept asking my fiancé what perfume I had on. Will treasure this one.',
    verified: true,
  },
  {
    name: 'Daniel Martinez',
    location: 'Los Angeles, USA',
    product: 'Il Sovrano',
    rating: 5,
    date: 'October 2025',
    title: 'The compliment magnet',
    body: 'I have bought a lot of fragrances in my life and few get this reaction. Smooth, expensive, and long-lasting. The kiosk experience was top class too — they really take their time with you.',
    verified: true,
  },
  {
    name: 'Aisha Verma',
    location: 'Jaipur, India',
    product: 'Veleno D’Oro',
    rating: 5,
    date: 'October 2025',
    title: 'Pure luxury',
    body: 'From the first spray it feels indulgent. Saffron and rose with a warm trail that stays close to the skin. It has become my go-to for every special occasion.',
    verified: true,
  },
]
